import type {
  Action,
  AssetOption,
  Difficulty,
  HistoryEntry,
  RiskRules,
  ScenarioType,
} from "@/lib/types";

export const APP_NAME = "Pyth Oracle Gym";

export const ASSET_OPTIONS: AssetOption[] = [
  {
    key: "BTC",
    label: "BTC / USD",
    fullSymbol: "Crypto.BTC/USD",
    historySymbol: "Crypto.BTC/USD",
    assetType: "crypto",
    basePrice: 72250,
    channel: "real_time",
    resolution: "15",
    hermesId: "e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43",
    pythLazerId: 1,
    description: "BITCOIN / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "ETH",
    label: "ETH / USD",
    fullSymbol: "Crypto.ETH/USD",
    historySymbol: "Crypto.ETH/USD",
    assetType: "crypto",
    basePrice: 3975,
    channel: "real_time",
    resolution: "15",
    hermesId: "ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
    pythLazerId: 2,
    description: "ETHEREUM / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "SOL",
    label: "SOL / USD",
    fullSymbol: "Crypto.SOL/USD",
    historySymbol: "Crypto.SOL/USD",
    assetType: "crypto",
    basePrice: 176,
    channel: "real_time",
    resolution: "15",
    hermesId: "ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d",
    pythLazerId: 6,
    description: "SOLANA / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "BNB",
    label: "BNB / USD",
    fullSymbol: "Crypto.BNB/USD",
    historySymbol: "Crypto.BNB/USD",
    assetType: "crypto",
    basePrice: 635,
    channel: "real_time",
    resolution: "15",
    hermesId: "2f95862b045670cd22bee3114c39763a4a08beeb663b145d283c31d7d1101c4f",
    pythLazerId: 4,
    description: "BINANCE COIN / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "XRP",
    label: "XRP / USD",
    fullSymbol: "Crypto.XRP/USD",
    historySymbol: "Crypto.XRP/USD",
    assetType: "crypto",
    basePrice: 2.45,
    channel: "real_time",
    resolution: "15",
    hermesId: "ec5d399846a9209f3fe5881d70aae9268c94339ff9817e8d18ff19fa05eea1c8",
    pythLazerId: 7,
    description: "RIPPLE / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "ADA",
    label: "ADA / USD",
    fullSymbol: "Crypto.ADA/USD",
    historySymbol: "Crypto.ADA/USD",
    assetType: "crypto",
    basePrice: 0.98,
    channel: "real_time",
    resolution: "15",
    hermesId: "2a01deaec9e51a579277b34b122399984d0bbf57e2458a7e42fecd2829867a0d",
    pythLazerId: 8,
    description: "CARDANO / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "DOGE",
    label: "DOGE / USD",
    fullSymbol: "Crypto.DOGE/USD",
    historySymbol: "Crypto.DOGE/USD",
    assetType: "crypto",
    basePrice: 0.32,
    channel: "real_time",
    resolution: "15",
    hermesId: "dcef50dd0a4cd2dcc17e45df1676dcb336a11a61c69df7a0299b0150c672d25c",
    pythLazerId: 9,
    description: "DOGECOIN / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "AVAX",
    label: "AVAX / USD",
    fullSymbol: "Crypto.AVAX/USD",
    historySymbol: "Crypto.AVAX/USD",
    assetType: "crypto",
    basePrice: 42,
    channel: "real_time",
    resolution: "15",
    hermesId: "93da3352f9f1d105fdfe4971cfa80e9dd777bfc5d0f683ebb6e1294b92137bb7",
    pythLazerId: 10,
    description: "AVALANCHE / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "MATIC",
    label: "POL / USD",
    fullSymbol: "Crypto.POL/USD",
    historySymbol: "Crypto.POL/USD",
    assetType: "crypto",
    basePrice: 0.52,
    channel: "real_time",
    resolution: "15",
    hermesId: "ffd11c5a1cfd42f80afb2df4d9f264c15f956d68153335374ec10722edd70472",
    pythLazerId: 11,
    description: "POLYGON / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "LINK",
    label: "LINK / USD",
    fullSymbol: "Crypto.LINK/USD",
    historySymbol: "Crypto.LINK/USD",
    assetType: "crypto",
    basePrice: 22,
    channel: "real_time",
    resolution: "15",
    hermesId: "8ac0c70fff57e9aefdf5edf44b51d62c2d433653cbb2cf5cc06bb115af04d221",
    pythLazerId: 12,
    description: "CHAINLINK / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "UNI",
    label: "UNI / USD",
    fullSymbol: "Crypto.UNI/USD",
    historySymbol: "Crypto.UNI/USD",
    assetType: "crypto",
    basePrice: 13,
    channel: "real_time",
    resolution: "15",
    hermesId: "78d185a741d07edb3412b09008b7c5cfb9bbbd7d568bf00ba737b456ba171501",
    pythLazerId: 13,
    description: "UNISWAP / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "ATOM",
    label: "ATOM / USD",
    fullSymbol: "Crypto.ATOM/USD",
    historySymbol: "Crypto.ATOM/USD",
    assetType: "crypto",
    basePrice: 9.5,
    channel: "real_time",
    resolution: "15",
    hermesId: "b00b60f88b03a6a625a8d1c048c3f66653edf217439983d037e7222c4e612819",
    pythLazerId: 14,
    description: "COSMOS / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
  {
    key: "PYTH",
    label: "PYTH / USD",
    fullSymbol: "Crypto.PYTH/USD",
    historySymbol: "Crypto.PYTH/USD",
    assetType: "crypto",
    basePrice: 0.71,
    channel: "real_time",
    resolution: "15",
    hermesId: "0bbf28e9a841a1cc788f6a361b17ca072d0ea3098a1e5df1c3922d06719579ff",
    pythLazerId: 3,
    description: "PYTH NETWORK / US DOLLAR",
    exponent: -8,
    state: "stable",
    quoteCurrency: "USD",
  },
];

export const SCENARIO_OPTIONS: Array<{
  type: ScenarioType;
  label: string;
  pacing: string;
  copy: string;
}> = [
  {
    type: "breakout",
    label: "Breakout",
    pacing: "Momentum",
    copy: "Trend compression snaps into expansion. The challenge is entering conviction without chasing noise.",
  },
  {
    type: "crash",
    label: "Crash",
    pacing: "Defensive",
    copy: "A violent downside unwind punishes hesitation and overconfidence at the same time.",
  },
  {
    type: "chop",
    label: "Chop",
    pacing: "Patience",
    copy: "Whipsaw price action punishes overtrading and rewards restraint.",
  },
  {
    type: "fakeout",
    label: "Fakeout",
    pacing: "Trap-heavy",
    copy: "Momentum looks clean until the floor disappears. Read the trap before it reads you.",
  },
  {
    type: "slow-bleed",
    label: "Slow Bleed",
    pacing: "Grinding",
    copy: "A long, draining descent tests discipline more than reflexes.",
  },
  {
    type: "volatility-spike",
    label: "Volatility Spike",
    pacing: "Chaos",
    copy: "Wide candles and sharp reversals make risk framing as important as direction.",
  },
];

export const DIFFICULTY_OPTIONS: Array<{
  value: Difficulty;
  label: string;
  copy: string;
}> = [
  { value: "easy", label: "Easy", copy: "Cleaner structure and visible setups." },
  { value: "medium", label: "Medium", copy: "Balanced uncertainty and one meaningful shock." },
  { value: "chaos", label: "Chaos", copy: "Hidden shock, faster tape, thinner confidence." },
];

export const WINDOW_OPTIONS = [
  { value: 6, label: "6 hours" },
  { value: 12, label: "12 hours" },
  { value: 24, label: "24 hours" },
];

export const DEFAULT_RISK_RULES: RiskRules = {
  maxLossPct: 4,
  cooldownBars: 3,
  leverageCap: 2,
  patienceThreshold: 68,
};

export const ACTION_OPTIONS: Action[] = ["buy", "sell", "hold", "reduce", "wait", "hedge"];

export const ACTION_LABELS: Record<Action, string> = {
  buy: "Buy",
  sell: "Sell",
  hold: "Hold",
  reduce: "Reduce",
  wait: "Wait",
  hedge: "Hedge",
};

export const SEEDED_HISTORY: HistoryEntry[] = [
  {
    id: "seed-btc-breakout",
    assetLabel: "BTC / USD",
    scenarioLabel: "Breakout",
    modeLabel: "Human",
    total: 88,
    grade: "A-",
    completedAtLabel: "Mar 24, 2026",
    changePct: 6.8,
    summary: "Caught the expansion well, but paid a small consistency penalty for chasing the second leg.",
  },
  {
    id: "seed-sol-fakeout",
    assetLabel: "SOL / USD",
    scenarioLabel: "Fakeout",
    modeLabel: "Agent",
    total: 84,
    grade: "B+",
    completedAtLabel: "Mar 23, 2026",
    changePct: -4.2,
    summary: "The agent waited through the trap and handled the reversal with solid discipline.",
  },
  {
    id: "seed-eth-spike",
    assetLabel: "ETH / USD",
    scenarioLabel: "Volatility Spike",
    modeLabel: "Human",
    total: 79,
    grade: "B",
    completedAtLabel: "Mar 22, 2026",
    changePct: 5.5,
    summary: "Strong adaptation after the shock, but timer pressure clipped execution quality.",
  },
];
